Task 1:

Construct a random 3x28x28 NumPy array called original to represent an image and then convert this into into a 1x(3x28x28) array called flat. This converts it into a single row of pixels. Next, convert this to a 1D array (flatten the array using flat.flatten()). Print shape of all arrays. You may use the random function to generate the array.

In [4]:
import numpy as np
original = np.random.rand(3,28,28)

In [19]:
original.shape

(3, 28, 28)

In [16]:
flat = original.reshape(1,3,28,28)

In [18]:
flat.shape

(1, 3, 28, 28)

In [21]:
vector = flat.flatten()

In [23]:
vector.shape

(2352,)

Task 2: Print out the following:

dimension of the arrays.

memory address of the arrays (pointer).

shape of the arrays.

data types of the arrays.

In [33]:
# Dimensions of arrays

print(original.ndim)
print(flat.ndim)
print(vector.ndim)

3
4
1


In [34]:
# Shape of arrays

print(original.shape)
print(flat.shape)
print(vector.shape)

(3, 28, 28)
(1, 3, 28, 28)
(2352,)


In [37]:
# Data type of arrays

print(original.dtype)
print(flat.dtype)
print(vector.dtype)

float64
float64
float64


In [55]:
# Memory address of arrays

pointer, read_only_flag = original.__array_interface__['data']
pointer_1, read_only_flag = flat.__array_interface__['data']
pointer_2, read_only_flag = vector.__array_interface__['data']

In [56]:
print(pointer)
print(pointer_1)
print(pointer_2)

1749013158144
1749013158144
1749013222096


Task 3:

Construct a new array which is a negative of the original array, i.e, all elements are negative of those in the original array. Print the new array. Add the original and new arrays. Print the result.

In [60]:
negative_array = np.negative(original)

In [61]:
negative_array

array([[[-0.52131719, -0.27167922, -0.88671742, ..., -0.18447132,
         -0.85294559, -0.15175654],
        [-0.73184871, -0.49272661, -0.76136413, ..., -0.00878491,
         -0.24844721, -0.70644615],
        [-0.03349369, -0.96769629, -0.12926021, ..., -0.53994086,
         -0.94313529, -0.1955702 ],
        ...,
        [-0.05808202, -0.01307237, -0.40591367, ..., -0.65929184,
         -0.62269412, -0.53700196],
        [-0.94689123, -0.53117318, -0.40197326, ..., -0.60758817,
         -0.3854297 , -0.3581437 ],
        [-0.98494376, -0.01122851, -0.56957193, ..., -0.84954515,
         -0.39654863, -0.1463662 ]],

       [[-0.09924753, -0.73030774, -0.75665588, ..., -0.25063681,
         -0.7108475 , -0.89762728],
        [-0.37233307, -0.75993521, -0.60881059, ..., -0.01016888,
         -0.30826464, -0.98969588],
        [-0.94169965, -0.66514002, -0.41950917, ..., -0.18380316,
         -0.66029885, -0.86771963],
        ...,
        [-0.23958428, -0.58086008, -0.96197845, ..., -

In [62]:
add_array = original + negative_array

In [65]:
add_array

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

Task 4

A 3x28x28 basically means 28x28 matrices repeated three times. How would you access the first 10 elements of the 2nd row of the second 28x28 matrix? Consider the original array for this. Print the elements.

In [27]:
original[1][1][:10]

array([0.18028979, 0.94328566, 0.31979758, 0.74629313, 0.12587211,
       0.14414526, 0.68995129, 0.14598003, 0.21464729, 0.6555172 ])

Task 5

A 3x28x28 image means 3 channels of Red, Green, or Blue (Popularly known as RGB image). Each color channel has a height and width, which is 28X28 in this case. The entire picture can represented through this method. Print the shape of the Blue pixel matrix and its first 3 rows.

In [18]:
original[2].shape

(28, 28)

In [24]:
original[2][1:4]

array([[0.3030422 , 0.53491535, 0.60736965, 0.08845053, 0.47237174,
        0.31805409, 0.08105065, 0.48970171, 0.55229492, 0.39867649,
        0.90831271, 0.33949975, 0.07867391, 0.9019824 , 0.27265574,
        0.25540089, 0.05017877, 0.77491306, 0.27203648, 0.01268239,
        0.67567188, 0.72385543, 0.89926971, 0.70090066, 0.03311328,
        0.04054488, 0.2832992 , 0.21590293],
       [0.58983212, 0.97150023, 0.19259755, 0.2679258 , 0.99361039,
        0.5957245 , 0.64363189, 0.84796331, 0.38517271, 0.38055884,
        0.9120018 , 0.72865008, 0.6952161 , 0.71400618, 0.45363408,
        0.9630346 , 0.30586971, 0.65304095, 0.54401455, 0.90845528,
        0.06658825, 0.17741271, 0.54517849, 0.15040657, 0.6074952 ,
        0.45727074, 0.05946657, 0.99595466],
       [0.10298573, 0.48708027, 0.99875361, 0.95653075, 0.32105701,
        0.36769276, 0.15530146, 0.60157741, 0.79587629, 0.42441526,
        0.50198682, 0.26430421, 0.55013545, 0.96619581, 0.94677442,
        0.1058469 , 0.6758

Task 6

Create a 1 dimensional numpy array of the first 50 even numbers. Convert this to a 10x5 numpy array and print its transpose.

In [5]:
even_array = np.arange(2,101,2)
even_array

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [75]:
new_array = np.reshape(even_array, (10,5))
new_array

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [76]:
new_array.transpose()

array([[  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

Task 7

Consider the 10x5 array created in Task 6. Find the mean of each row and column. You may use in built functions or write your own code.

In [98]:
new_array[:,0].mean(), new_array[:,1].mean()

(47.0, 49.0)

Task 8

Can we create a 3x3 array of the first 50 even numbers? Why or why not? What are other values of m and n for which mxn dimension is allowed for 50 elements?

In [6]:
even_array

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [7]:
even_array.reshape(3,3)

ValueError: cannot reshape array of size 50 into shape (3,3)

In [8]:
print("We cannot create an array of 3x3 because the total number of elements are not multiples of 3. The other values for which mxn dimensions are allowed are 2,5,10,25.")

We cannot create an array of 3x3 because the total number of elements are not multiples of 3. The other values for which mxn dimensions are allowed are 2,5,10,25.
